id: ICCF50AF5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-12T22:35:08+00:00'
last_modified: '2022-06-10T04:13:23.256562+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W22068
  title: མངའ་རིས་གསེར་རྫོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6856':
      image_group_id: I1KG17259
      title: Volume 1 of mnga' ris gser rdzong
      total_pages: 252
      order: 1
      base_file: 6856.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
